//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareeriaDevsApp.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class OmaSisalto
    {
        public int omaSisalto_Id { get; set; }
        public byte[] omatAsetukset { get; set; }
        public byte[] omaKuva { get; set; }
        public byte[] omaTeksti { get; set; }
        public Nullable<int> opiskelija_Id { get; set; }
    
        public virtual Opiskelija Opiskelija { get; set; }
    }
}
