//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareeriaDevsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opiskelija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opiskelija()
        {
            this.Login = new HashSet<Login>();
            this.OmaSisalto = new HashSet<OmaSisalto>();
            this.PuhelinNumero = new HashSet<PuhelinNumero>();
            this.Viesti = new HashSet<Viesti>();
            this.Sahkoposti = new HashSet<Sahkoposti>();
        }
    
        public int opiskelija_Id { get; set; }
        public string etunimi { get; set; }
        public string sukunimi { get; set; }
        public Nullable<int> postitoimipaikka_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OmaSisalto> OmaSisalto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuhelinNumero> PuhelinNumero { get; set; }
        public virtual Postitoimipaikka Postitoimipaikka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viesti> Viesti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sahkoposti> Sahkoposti { get; set; }
    }
}
