//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareeriaDevsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuhelinNumero
    {
        public int puhelinNumero_Id { get; set; }
        public string numero { get; set; }
        public Nullable<int> puhelinTyyppi_Id { get; set; }
        public Nullable<int> opiskelija_Id { get; set; }
        public Nullable<int> yritys_Id { get; set; }
    
        public virtual Opiskelija Opiskelija { get; set; }
        public virtual PuhelinTyyppi PuhelinTyyppi { get; set; }
        public virtual Yritys Yritys { get; set; }
    }
}
